[workspace]
resolver = "2"
members = [
    'node',
    'runtime',
    'pallets/cere-contracts',
    'pallets/cere-contracts/primitives',
    'contracts/upgradable_set_code_hash',
]

[profile.release]
panic = 'unwind'
