[workspace]
resolver = "2"
members = [
    'node',
    'runtime',
]

[profile.release]
panic = 'unwind'

[patch."https://github.com/paritytech/substrate"]
frame-executive = { path = "../substrate/frame/executive"}
frame-support = { path = "../substrate/frame/support"}
frame-system = { path = "../substrate/frame/system"}
frame-system-rpc-runtime-api = { path = "../substrate/frame/system/rpc/runtime-api"}
pallet-assets = { path = "../substrate/frame/assets"}
pallet-authorship = { path = "../substrate/frame/authorship"}
pallet-balances = { path = "../substrate/frame/balances"}
pallet-contracts = { path = "../substrate/frame/contracts"}
pallet-contracts-primitives = { path = "../substrate/frame/contracts/primitives"}
# pallet-randomness-collective-flip = { path = "../substrate/frame/randomness-collective-flip"}
pallet-insecure-randomness-collective-flip = { path = "../substrate/frame/insecure-randomness-collective-flip"}
pallet-sudo = { path = "../substrate/frame/sudo"}
pallet-timestamp = { path = "../substrate/frame/timestamp"}
pallet-transaction-payment = { path = "../substrate/frame/transaction-payment"}
pallet-transaction-payment-rpc = { path = "../substrate/frame/transaction-payment/rpc" }
pallet-transaction-payment-rpc-runtime-api = { path = "../substrate/frame/transaction-payment/rpc/runtime-api"}
pallet-utility = { path = "../substrate/frame/utility"}
sc-basic-authorship = { path = "../substrate/client/basic-authorship" }
sc-cli = { path = "../substrate/client/cli" }
sc-client-api = { path = "../substrate/client/api" }
sc-consensus = { path = "../substrate/client/consensus/common" }
sc-consensus-manual-seal = { path = "../substrate/client/consensus/manual-seal" }
sc-executor = { path = "../substrate/client/executor" }
sc-keystore = { path = "../substrate/client/keystore" }
sc-rpc = { path = "../substrate/client/rpc" }
sc-rpc-api = { path = "../substrate/client/rpc-api" }
sc-service = { path = "../substrate/client/service" }
sc-telemetry = { path = "../substrate/client/telemetry" }
sc-transaction-pool = { path = "../substrate/client/transaction-pool" }
sc-transaction-pool-api = { path = "../substrate/client/transaction-pool/api" }
sp-api = { path = "../substrate/primitives/api" }
sp-block-builder = { path = "../substrate/primitives/block-builder" }
sp-blockchain = { path = "../substrate/primitives/blockchain" }
sp-core = { path = "../substrate/primitives/core" }
sp-inherents = { path = "../substrate/primitives/inherents"}
sp-weights = { path = "../substrate/primitives/weights"}
sp-io = { path = "../substrate/primitives/io"}
sp-offchain = { path = "../substrate/primitives/offchain"}
sp-runtime = { path = "../substrate/primitives/runtime" }
sp-session = { path = "../substrate/primitives/session"}
sp-std = { path = "../substrate/primitives/std"}
sp-timestamp = { path = "../substrate/primitives/timestamp" }
sp-transaction-pool = { path = "../substrate/primitives/transaction-pool"}
sp-version = { path = "../substrate/primitives/version"}
substrate-build-script-utils = { path = "../substrate/utils/build-script-utils" }
substrate-frame-rpc-system = { path = "../substrate/utils/frame/rpc/system" }
substrate-wasm-builder = { path = "../substrate/utils/wasm-builder"}
