[package]
name = "contracts-node-runtime"
version = "0.31.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Runtime configured for smart contracts via `pallet-contracts`."
edition = "2021"
license = "Unlicense"
homepage = "https://github.com/paritytech/substrate-contracts-node"
repository = "https://github.com/paritytech/substrate-contracts-node"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

pallet-authorship = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-authorship", default-features = false }
pallet-assets = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-assets", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-balances", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", package = "frame-support", default-features = false }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-insecure-randomness-collective-flip", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-sudo", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", package = "frame-system", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-timestamp", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-transaction-payment", default-features = false }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk", package = "frame-executive", default-features = false }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-api", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-block-builder", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-core", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-inherents", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-offchain", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-runtime", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-io", default-features = false }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-session", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-std", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-transaction-pool", default-features = false }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-version", default-features = false }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", package = "sp-weights", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-utility", default-features = false }

# Used for the node's RPCs
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk", package = "frame-system-rpc-runtime-api", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-transaction-payment-rpc-runtime-api", default-features = false }

# Contracts specific packages
pallet-contracts = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-contracts", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/polkadot-sdk", package = "pallet-contracts-primitives", default-features = false }

[build-dependencies]
substrate-wasm-builder =  { git = "https://github.com/paritytech/polkadot-sdk", package = "substrate-wasm-builder", optional = true }

[features]
default = [
	"std",
]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sp-weights/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-assets/std",
	"substrate-wasm-builder",
]
